import os
import sys
import json
import tempfile
import shutil
import subprocess
from typing import Optional
from typing_extensions import TypedDict
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage
from langgraph.graph import StateGraph, END

load_dotenv()

# LangSmith tracing — enabled when LANGSMITH_API_KEY is present in env
_langsmith_key = os.getenv("LANGSMITH_API_KEY")
if _langsmith_key:
    os.environ["LANGCHAIN_TRACING_V2"] = "true"
    os.environ["LANGCHAIN_API_KEY"] = _langsmith_key
    os.environ["LANGCHAIN_PROJECT"] = "ai-orchestrator-assignment-1"
    print("[LANGSMITH] Tracing enabled")

# tickets to process

TICKETS = [
    {
        "id": "DATA-001",
        "summary": "ISO date parser utility",
        "description": """
            Write a function `parse_iso_date(date_str: str) -> dict` that:
            - Accepts a string in ISO 8601 format (e.g. '2024-03-15T14:30:00Z')
            - Returns a dict with keys: year, month, day, hour, minute, second, timezone
            - Raises ValueError with a helpful message for invalid inputs
            - Includes at least 3 example calls in the __main__ block
        """,
    },
    {
        "id": "DATA-002",
        "summary": "Binary search implementation",
        "description": """
            Write a function `binary_search(arr: list[int], target: int) -> int` that:
            - Searches a sorted list for target
            - Returns the index if found, or -1 if not found
            - Uses iterative (not recursive) implementation
            - Includes a __main__ block that tests edge cases:
              empty list, single element, first element, last element, not found
        """,
    },
    {
        "id": "DATA-003",
        "summary": "CSV row counter utility",
        "description": """
            Write a function `count_csv_rows(filepath: str, skip_header: bool = True) -> int` that:
            - Reads a CSV file and returns the number of data rows
            - When skip_header=True (default), excludes the first row from the count
            - Raises FileNotFoundError if the path doesn't exist
            - Raises ValueError if the file is empty
            - In __main__, create a small in-memory CSV, write it to a temp file,
              run the function, and print the result
        """,
    },
]

# everything the graph nodes pass around between each other


class AgentState(TypedDict):
    ticket: dict           # The Jira ticket being processed
    # Numbered implementation plan from Planner (formatted text)
    plan: str
    plan_json: dict        # Structured plan from Planner (parsed JSON)
    code: str              # Python code generated by Coder
    compiler_output: str   # stdout/stderr from running the code
    test_code: str         # pytest code generated by Test Runner
    test_output: str       # stdout/stderr from running tests
    coverage_report: str   # pytest-cov coverage summary
    # current error message; None after a successful step
    error: Optional[str]
    retry_count: int       # how many retry cycles have occurred
    # if True, force a compiler error on attempt 1 to demo the retry loop
    simulate_failure: bool


# single shared model instance — all nodes use this
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

# JSON-mode variant used by the Planner for structured output
llm_json = llm.bind(response_format={"type": "json_object"})

# LLM sometimes wraps output in ```python blocks even when told not to


def _strip_fences(text: str) -> str:
    if "```python" in text:
        return text.split("```python")[1].split("```")[0].strip()
    if "```" in text:
        return text.split("```")[1].split("```")[0].strip()
    return text.strip()

# Node 1 — Planner


def planner_node(state: AgentState) -> AgentState:
    print("\n[PLANNER] Creating implementation plan (structured JSON)...")
    ticket = state["ticket"]

    response = llm_json.invoke([
        SystemMessage(content=(
            "You are a software architect. Your job is to create detailed implementation plans. "
            "IMPORTANT: Do NOT write any code whatsoever. Each step must describe WHAT to do, not HOW to code it.\n\n"
            "You MUST respond with a JSON object containing exactly these keys:\n"
            '  "summary": a one-sentence overview of the implementation\n'
            '  "steps": an array of strings, each a clear numbered-free implementation step'
        )),
        HumanMessage(content=(
            f"Create an implementation plan for this Jira ticket:\n\n"
            f"ID: {ticket['id']}\n"
            f"Summary: {ticket['summary']}\n"
            f"Description: {ticket['description']}\n\n"
            "Return only a JSON object with 'summary' and 'steps' keys. No code allowed."
        )),
    ])

    plan_json = json.loads(response.content)
    steps = plan_json.get("steps", [])
    plan_text = "\n".join(f"{i + 1}. {step}" for i, step in enumerate(steps))

    print(f"[PLANNER] Plan ready — {len(steps)} steps")
    print(f"  Summary: {plan_json.get('summary', '')}")
    print(plan_text)
    return {**state, "plan": plan_text, "plan_json": plan_json}

# Node 2 — Coder


def coder_node(state: AgentState) -> AgentState:
    retry_count = state.get("retry_count", 0)
    error = state.get("error")
    print(f"\n[CODER] Generating code (attempt {retry_count + 1})...")

    base_prompt = (
        f"Jira Ticket: {state['ticket']['id']} — {state['ticket']['summary']}\n\n"
        f"Ticket Description:\n{state['ticket']['description']}\n\n"
        f"Implementation Plan:\n{state['plan']}\n\n"
        "Requirements:\n"
        "- Write complete, runnable Python code\n"
        "- Include all necessary imports\n"
        "- Follow every requirement in the ticket description exactly\n"
        "- The script must run successfully with `python solution.py`\n"
    )

    if error and retry_count > 0:
        user_prompt = (
            base_prompt
            + f"\nPREVIOUS ATTEMPT FAILED WITH THIS ERROR — fix it:\n\n{error}\n\n"
            "Write corrected Python code that resolves the error above."
        )
    else:
        user_prompt = base_prompt + "\nWrite the complete Python implementation now:"

    response = llm.invoke([
        SystemMessage(content=(
            "You are an expert Python developer. Output only raw Python code — "
            "no explanations, no markdown fences, no commentary."
        )),
        HumanMessage(content=user_prompt),
    ])

    code = _strip_fences(response.content)
    print(f"[CODER] Code ready — {len(code.splitlines())} lines")
    return {**state, "code": code}

# Node 3 — Compiler


def compiler_node(state: AgentState) -> AgentState:
    print("\n[COMPILER] Running generated code...")

    # simulated first-attempt failure so the retry loop is always visible in demos
    if state.get("simulate_failure") and state.get("retry_count", 0) == 0:
        msg = "Simulated Error: NameError: name 'undefined_var' is not defined (line 5)"
        print("[COMPILER] SIMULATED FAILURE")
        return {**state, "compiler_output": msg, "error": msg}

    tmp_dir = tempfile.mkdtemp(prefix="agent_compile_")
    code_path = os.path.join(tmp_dir, "solution.py")

    try:
        with open(code_path, "w") as f:
            f.write(state["code"])

        result = subprocess.run(
            [sys.executable, code_path],
            capture_output=True,
            text=True,
            timeout=30,
            cwd=tmp_dir,
        )

        output = (result.stdout + result.stderr).strip()

        if result.returncode != 0:
            error_msg = f"Compile/Runtime Error (exit {result.returncode}):\n{output}"
            print(f"[COMPILER] FAILED\n{output}")
            return {**state, "compiler_output": output, "error": error_msg}

        print(f"[COMPILER] SUCCESS\n{output if output else '(no stdout)'}")
        return {**state, "compiler_output": output, "error": None}

    except subprocess.TimeoutExpired:
        msg = "Code execution timed out after 30 seconds."
        print("[COMPILER] TIMEOUT")
        return {**state, "compiler_output": msg, "error": msg}
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)

# Node 4 — Test Runner


def test_runner_node(state: AgentState) -> AgentState:
    print("\n[TEST_RUNNER] Generating and running pytest tests...")

    # no point running tests if the code didn't even compile
    if state.get("error"):
        print("[TEST_RUNNER] Skipping — compile step already failed.")
        return state

    tmp_dir = tempfile.mkdtemp(prefix="agent_test_")
    code_path = os.path.join(tmp_dir, "solution.py")
    test_path = os.path.join(tmp_dir, "test_solution.py")

    try:
        with open(code_path, "w") as f:
            f.write(state["code"])

        # generate tests against the actual code so they match what was produced
        response = llm.invoke([
            SystemMessage(content=(
                "You are a pytest expert. Write pytest tests for the provided Python code.\n"
                "Rules:\n"
                "- Import only from 'solution' (the module being tested)\n"
                "- All test functions must start with 'test_'\n"
                "- ONLY test behavior explicitly described in the ticket spec — do not invent edge cases\n"
                "- When creating temp files in tests, write the exact number of rows you assert against\n"
                "- Do NOT include a __main__ block\n"
                "- Output only raw Python code — no markdown, no explanations"
            )),
            HumanMessage(content=(
                f"Ticket spec:\n{state['ticket']['description']}\n\n"
                f"Write a pytest test file for this solution.py:\n\n"
                f"{state['code']}\n\n"
                "Only test what the spec above explicitly requires. Import from 'solution'."
            )),
        ])

        test_code = _strip_fences(response.content)
        print(
            f"[TEST_RUNNER] Tests generated — {len(test_code.splitlines())} lines")

        with open(test_path, "w") as f:
            f.write(test_code)

        result = subprocess.run(
            [
                sys.executable, "-m", "pytest", test_path, "-v", "--tb=short",
                "--cov=solution", "--cov-report=term-missing", "--no-header",
            ],
            capture_output=True,
            text=True,
            timeout=60,
            cwd=tmp_dir,
        )

        test_output = (result.stdout + result.stderr).strip()

        # extract only the coverage table (starts at the "Name ... Stmts" header line)
        coverage_report = ""
        lines = test_output.splitlines()
        for i, line in enumerate(lines):
            if line.startswith("Name") and "Stmts" in line:
                coverage_report = "\n".join(lines[i:])
                break

        if result.returncode != 0:
            error_msg = f"Test Failures:\n{test_output}"
            print(f"[TEST_RUNNER] FAILED\n{test_output}")
            return {**state, "test_code": test_code, "test_output": test_output,
                    "coverage_report": coverage_report, "error": error_msg}

        print(f"[TEST_RUNNER] ALL TESTS PASSED\n{test_output}")
        return {**state, "test_code": test_code, "test_output": test_output,
                "coverage_report": coverage_report, "error": None}

    except subprocess.TimeoutExpired:
        msg = "Test execution timed out after 60 seconds."
        print("[TEST_RUNNER] TIMEOUT")
        return {**state, "test_code": "", "test_output": msg, "error": msg}
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)

# Node 5 — Error Handler


def error_handler_node(state: AgentState) -> AgentState:
    new_count = state.get("retry_count", 0) + 1
    print(f"\n[ERROR_HANDLER] Retry {new_count}/3")
    print(f"[ERROR_HANDLER] Error: {state.get('error', '')}")
    return {**state, "retry_count": new_count}

# routes back to coder on failure, or ends the graph if we're out of retries


def should_retry(state: AgentState) -> str:
    if state.get("error") and state.get("retry_count", 0) < 3:
        return "error_handler"
    return END

# wire up all the nodes and edges


def build_graph():
    graph = StateGraph(AgentState)

    graph.add_node("planner", planner_node)
    graph.add_node("coder", coder_node)
    graph.add_node("compiler", compiler_node)
    graph.add_node("test_runner", test_runner_node)
    graph.add_node("error_handler", error_handler_node)

    graph.set_entry_point("planner")
    graph.add_edge("planner", "coder")
    graph.add_edge("coder", "compiler")
    graph.add_edge("compiler", "test_runner")
    graph.add_conditional_edges("test_runner", should_retry)
    graph.add_edge("error_handler", "coder")

    return graph.compile()

# run a single ticket end-to-end


if __name__ == "__main__":
    ticket = TICKETS[1]

    separator = "=" * 60
    print(f"\n{separator}")
    print(f"Ticket : {ticket['id']} — {ticket['summary']}")
    print(separator)

    agent = build_graph()

    initial_state: AgentState = {
        "ticket": ticket,
        "plan": "",
        "plan_json": {},
        "code": "",
        "compiler_output": "",
        "test_code": "",
        "test_output": "",
        "coverage_report": "",
        "error": None,
        "retry_count": 0,
        "simulate_failure": False,  # set to False to run normally
    }

    result = agent.invoke(initial_state)

    print(f"\n{separator}")
    print("FINAL RESULT")
    print(separator)
    print(f"Retries used : {result['retry_count']}")
    status = "SUCCESS" if not result.get(
        "error") else "FAILED (max retries reached)"
    print(f"Final status : {status}")

    print("\n--- Generated Code ---")
    print(result["code"])
    print("\n--- Compiler Output ---")
    print(result["compiler_output"] or "(no output)")
    if result.get("test_output"):
        print("\n--- Test Output ---")
        print(result["test_output"])
    if result.get("error"):
        print(f"\nLast error:\n{result['error']}")

    # write results to output/
    output_dir = os.path.join(os.path.dirname(__file__), "output")
    os.makedirs(output_dir, exist_ok=True)
    output_file = os.path.join(output_dir, f"{ticket['id']}_result.txt")

    with open(output_file, "w") as f:
        f.write(f"Ticket : {ticket['id']} — {ticket['summary']}\n")
        f.write(f"Status : {status}\n")
        f.write(f"Retries: {result['retry_count']}\n")
        f.write(f"\n{'=' * 60}\nPLAN (STRUCTURED JSON)\n{'=' * 60}\n")
        f.write(json.dumps(result.get("plan_json", {}), indent=2) + "\n")
        f.write(f"\n{'=' * 60}\nPLAN (FORMATTED)\n{'=' * 60}\n")
        f.write(result.get("plan", "") + "\n")
        f.write(f"\n{'=' * 60}\nGENERATED CODE\n{'=' * 60}\n")
        f.write(result.get("code", "") + "\n")
        f.write(f"\n{'=' * 60}\nCOMPILER OUTPUT\n{'=' * 60}\n")
        f.write(result.get("compiler_output", "(no output)") + "\n")
        f.write(f"\n{'=' * 60}\nTEST CODE\n{'=' * 60}\n")
        f.write(result.get("test_code", "") + "\n")
        f.write(f"\n{'=' * 60}\nTEST OUTPUT\n{'=' * 60}\n")
        f.write(result.get("test_output", "") + "\n")
        if result.get("error"):
            f.write(f"\n{'=' * 60}\nLAST ERROR\n{'=' * 60}\n")
            f.write(result["error"] + "\n")

    print(f"\nOutput saved to: {output_file}")
